FROM python:3

WORKDIR /app

RUN apt update && apt upgrade -y
RUN apt install git -y
RUN git clone https://github.com/don9x2e/k8s-movie-info.git
RUN cp k8s-movie-info/movie-flask/* . 
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "./app.py"]

