apiVersion: v1
kind: Service
metadata:
  name: movieinfo-svc-flask
spec:
  type: NodePort
  selector:
    app: movie-flask
  ports:
   - name: movie-flask
     port: 31234
     protocol: TCP
     targetPort: 5000
     nodePort: 31234
