apiVersion: v1
kind: Service
metadata:
  name: movieinfo-svc-nginx
spec:
  type: NodePort
  selector:
    app: movie-nginx
  ports:
   - name: movie-nginx
     port: 32233
     protocol: TCP
     targetPort: 80
     nodePort: 32233
